/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.34
 * Generated at: 2014-05-15 23:47:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"utf-8\" />\n");
      out.write("\t<title>Juliett Home</title>\n");
      out.write("\t<meta name=\"generator\" content=\"BBEdit 10.5\" />\n");
      out.write("\t\n");
      out.write("\t<!-- import our css -->\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\t<link href=\"css/bootstrap.css\" rel=\"stylesheet\">\n");
      out.write("\t<link href=\"css/juliett.css\" rel=\"stylesheet\">\n");
      out.write("\t\n");
      out.write("\t<!-- import jquery and our js-->\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/juliett.js\"></script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body> \n");
      out.write("<div class=\"jumbotron\">\n");
      out.write("  <h1>Schedule for you!</h1>\n");
      out.write("  <p>Are your still struggling with arranging your courses for next quarter? \n");
      out.write("  <br>Here, you just need to enter some basic information and personal prenference. \n");
      out.write("  <br>We'll find the best course schedules for you!</p>\n");
      out.write("  <p><a class=\"btn btn-primary btn-lg\" herf=\"#startpoint1\">Try it Â»</a></p>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<a id=\"startpoint1\"></a>\n");
      out.write("\t<h id = \"teamname\">Team Juliett</h>\n");
      out.write("\t<div>\n");
      out.write("\t\tPut in your name:<input id=\"username\">\n");
      out.write("\t\t<button id=\"nametest\" onclick>send</button>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    // This is a scriptlet.  Notice that the "date"
    // variable we declare here is available in the
    // embedded expression later on.
    System.out.println( "Evaluating date now" );
    java.util.Date date = new java.util.Date();

      out.write("\t\n");
      out.write("Hello!  The time is now \n");

    // This scriptlet generates HTML output
    out.println( String.valueOf( date ));
	out.println( "<br>Your machine's address is " );
	out.println( request.getRemoteHost());
	

      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
